remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Kevin Riexinger | Eure Stimme im Senat
description: Wahlseite zu den Senatswahlen 2022 /23
